INSERT INTO clients (name, table_number) VALUES ('marta', 4);
INSERT INTO clients (name, table_number) VALUES ('jacek', 7);
INSERT INTO clients (name, table_number) VALUES ('braian', 1);
INSERT INTO orders (client_idc, additional_info) VALUES (1, 'no tomato');
INSERT INTO orders (client_idc, additional_info) VALUES (2, 'extra fries');
INSERT INTO orders (client_idc, additional_info) VALUES (3, 'allergic to penauts');
INSERT INTO ingredients (ing_desc) VALUES ('fresh tomatos from polish farmers');
INSERT INTO ingredients (ing_desc) VALUES ('homemade buns freshly baked in our stove');
INSERT INTO dishes (dish_description, price_per_portion) VALUES ('spadzetti', 29.90);
INSERT INTO dishes (dish_description, price_per_portion) VALUES ('kotlecik schabowy', 24.30);
INSERT INTO dishes (dish_description, price_per_portion) VALUES ('szuszi', 38.50);