INSERT INTO clients (name, table_number) VALUES ('marta', 4);
INSERT INTO clients (name, table_number) VALUES ('jacek', 7);
INSERT INTO clients (name, table_number) VALUES ('braian', 1);
INSERT INTO orders (client_idc, additional_info) VALUES (1, 'no tomato');
INSERT INTO orders (client_idc, additional_info) VALUES (2, 'extra fries');
INSERT INTO orders (client_idc, additional_info) VALUES (3, 'allergic to penauts');
INSERT INTO ingredients (ing_desc) VALUES ('tomato');
INSERT INTO ingredients (ing_desc) VALUES ('bun');
INSERT INTO ingredients (ing_desc) VALUES ('lettuce');
INSERT INTO ingredients (ing_desc) VALUES ('beef');
INSERT INTO ingredients (ing_desc) VALUES ('pork');
INSERT INTO ingredients (ing_desc) VALUES ('chicken breast');
INSERT INTO ingredients (ing_desc) VALUES ('onion');
INSERT INTO ingredients (ing_desc) VALUES ('pickle');
INSERT INTO ingredients (ing_desc) VALUES ('mayo');
INSERT INTO ingredients (ing_desc) VALUES ('noodles');
INSERT INTO ingredients (ing_desc) VALUES ('potatoes');
INSERT INTO ingredients (ing_desc) VALUES ('rice');
INSERT INTO ingredients (ing_desc) VALUES ('fish');
INSERT INTO ingredients (ing_desc) VALUES ('cheese');
INSERT INTO dishes (dish_description, price_per_portion) VALUES ('spadzetti', 29.90);
INSERT INTO dishes (dish_description, price_per_portion) VALUES ('kotlecik schabowy', 24.30);
INSERT INTO dishes (dish_description, price_per_portion) VALUES ('szuszi', 38.50);
INSERT INTO orders_dishes (orders_ido, dishes_idd, quantity) VALUES (1, 1, 1), (1, 2, 3), (2, 3, 2), (3, 2, 1); 
INSERT INTO dishes_ingredients (dishes_idd, ingredients_idi) VALUES (1, 1), (1, 4), (1, 10), (2, 5), (2, 11), (3, 12), (3, 13);